### ISSUE TITLE
Would that make sense to use Red::Database?

### ISSUE THREAD

**Issue by FCO** [jonathanstowe/Tinky-DB#1]
https://github.com/jonathanstowe/Tinky-DB/blob/0a86878d041976e9b55b1186b5b561e5f80fcdff/t/020-basic.t#L8
If you only need the `database` function, wouldn’t be better use `Red::Database`?

**Comment by jonathanstowe** [comment]
It would but I was lazy 😎

**Comment by jonathanstowe** [comment]
Well there's a thing.  If I change the t/020-basic.t to ```use Red::Database``` it gets to the lines that do

```perl6
class Foo does Tinky::DB::Object {
}
```
At which point it proceeds to use up all the memory and CPU for no obvious reason.  Which is odd.  Haven't got enough information to know where to start looking at the moment.

**Comment by FCO** [comment]
Strange... I’ll try that when I have some time...

**Comment by jonathanstowe** [comment]
Having sprinkled a few diags around in the test it seems it is specifically the grep statement on the Work flow. But it definitely not doing an actual query at the time.  All very odd.

**Comment by jonathanstowe** [comment]
Ah, it's the lack of the imports from ```Red::Operators```,  which I assume means that uses the standard operators and goes down a rabbit hole as a consequence..

Probably need to think about the way those imports are being handled.
